### ISSUE TITLE
Failed while attempting to save the changes to the Tag Rule. 

### ISSUE THREAD

**Issue by GabrielLasso** [curiefense/curiefense#537]
**Describe the bug**
I got "Failed while attempting to save the changes to the Tag Rule." whenever i try to save a Tag Rule in a new installation.

**To Reproduce**
1. git clone
2. docker-compose up
3. Access http://curie.demo:30080
4. Create a new tag rule and save it.

**Expected behavior**

**Screenshots**

![imagem_2021-08-04_113910](https://user-images.githubusercontent.com/12103372/128200752-5581ae40-1773-4519-8516-d1485937c159.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Opera and Firefox

**Additional context**
docker-compose logs:

```
confserver       | [] is too short
confserver       | 
confserver       | Failed validating 'minItems' in schema['properties']['tags']:
confserver       |     {'description': 'Tags associations',
confserver       |      'items': {'type': 'string'},
confserver       |      'minItems': 1,
confserver       |      'title': 'Tags List',
confserver       |      'type': 'array',
confserver       |      'uniqueItems': True}
confserver       | 
confserver       | On instance['tags']:
confserver       |     []
confserver       | [2021-08-04 14:30:20,120] ERROR in app: Exception on /api/v1/configs/master/d/tagrules/e/ac750b822d49/ [PUT]
confserver       | Traceback (most recent call last):
confserver       |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
confserver       |     rv = self.dispatch_request()
confserver       |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
confserver       |     return self.view_functions[rule.endpoint](**req.view_args)
confserver       |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
confserver       |     resp = resource(*args, **kwargs)
confserver       |   File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
confserver       |     return self.dispatch_request(*args, **kwargs)
confserver       |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
confserver       |     resp = meth(*args, **kwargs)
confserver       |   File "/usr/local/lib/python3.8/site-packages/curieconf/confserver/v1/api.py", line 624, in put
confserver       |     abort(500, "schema mismatched")
confserver       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 772, in abort
confserver       |     return _aborter(status, *args, **kwargs)
confserver       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 753, in __call__
confserver       |     raise self.mapping[code](*args, **kwargs)
confserver       | werkzeug.exceptions.InternalServerError: 500 Internal Server Error: schema mismatched
```

HEAD at 52e01aab297ba1817a198cd02ea2666874eb004b

**Comment by GabrielLasso** [comment]
Nevermind, I figured out what I did wrong
