### ISSUE TITLE
Curietasker docker image has missing python package

### ISSUE THREAD

**Issue by padziu** [curiefense/curiefense#725]
**Describe the bug**
Curietasker image (curiefense/curietasker:main) has missing python package.
https://hub.docker.com/layers/curiefense/curietasker/main/images/sha256-72b5975502f208d93643ea0059d161cb8f8ae3b4be92aa9de89238f35e451d1f?context=explore

docker logs curietasker

`Determining whether the tasks namespace should be created...
The tasks namespace already exists.
Traceback (most recent call last):
  File "/usr/local/bin/curietasker", line 3, in <module>
    from curietasker import main
  File "/usr/local/lib/python3.7/dist-packages/curietasker/__init__.py", line 7, in <module>
    from . import tasker
  File "/usr/local/lib/python3.7/dist-packages/curietasker/tasker.py", line 7, in <module>
    from . import tasks_list_updates
  File "/usr/local/lib/python3.7/dist-packages/curietasker/tasks_list_updates.py", line 7, in <module>
    from jsonschema import validate, ValidationError
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/_types.py", line 6, in <module>
    from pyrsistent import pmap
ModuleNotFoundError: No module named 'pyrsistent'`

**To Reproduce**
docker-compose -f compose/docker-compose.yaml
docker logs curietasker

**Expected behavior**
Old image (curiefense/curietasker:latest) working fine.

Docker version 20.10.12, build e91ed57

**Comment by chenstrace** [comment]
same issue

**Comment by WaylonTian** [comment]
same too

**Comment by Lastpixl** [comment]
Hello, this is indeed something that should be fixed. However, it can be ignored, and everything will still work properly.

**Comment by xavier-rbz** [comment]
Hello, this is indeed something that should be fixed. However, it can be ignored, and everything will still work properly.

**Comment by padziu** [comment]
@xavier-rbz This conatiner can't work properly beacuase it's restarting over and over again.
`afbf90d3d888   curiefense/curietasker:main                            "/usr/bin/dumb-init …"   5 days ago   Restarting (1) 20 seconds ago`

**Comment by xavier-rbz** [comment]
Indeed, this container endlessly restarts, and needs fixing to avoid that.
Its purpose is to run scheduled tasks; however, there are currently no such defined tasks in this repository. So, the container does not work, but this has no adverse effect on the other components, which still work normally.

**Comment by MicroOps-cn** [comment]
```shell
root@minikube:/# docker run -it --entrypoint /bin/bash curiefense/curietasker:main 
root@875194e1cadd:/# find -name pyrsistent 2>/dev/null 
./usr/lib/python3.7/site-packages/pyrsistent
root@875194e1cadd:/# python3 -c "import sys;print(sys.path)"
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']
```
By analyzing the python environment of the image, it is found that the package cannot be found because Python is installed under `/usr/lib/python3.7/site-packages` and `/usr/lib/python3.7/site-packages` is not in `PYTHONPATH`.

Further testing：
```shell
root@875194e1cadd:/curietasker# rm -rf /usr/lib/python3.7/site-packages/*pyrsistent* && cd /curietasker ; pip3 install --no-cache-dir . && echo "----------------------" && find / -name  pyrsistent 2>/dev/null 
Processing /curietasker
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from curietasker==0.6) (4.4.0)
Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (5.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (21.4.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.11.3)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema->curietasker==0.6)
  Downloading https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 767kB/s 
  Installing build dependencies ... done
Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.2.0)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema->curietasker==0.6) (3.8.0)
Installing collected packages: curietasker, pyrsistent
  Found existing installation: curietasker 0.6
    Uninstalling curietasker-0.6:
      Successfully uninstalled curietasker-0.6
  Running setup.py install for curietasker ... done
  Running setup.py install for pyrsistent ... done
Successfully installed curietasker-0.6 pyrsistent
----------------------
/usr/lib/python3.7/site-packages/pyrsistent
```
Try to remove the option `--no-cache-dir`. It is found that the option `--no-cache-dir` is not used when executing pip. There is no problem after the installation is completed
```
root@875194e1cadd:/curietasker# rm -rf /usr/lib/python3.7/site-packages/*pyrsistent* && cd /curietasker ; pip3 install . && echo "----------------------" && find / -name  pyrsistent 2>/dev/null 
Processing /curietasker
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from curietasker==0.6) (4.4.0)
Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (5.7.1)
Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.2.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (21.4.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.11.3)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema->curietasker==0.6)
  Downloading https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 369kB/s 
  Installing build dependencies ... done
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema->curietasker==0.6) (3.8.0)
Building wheels for collected packages: curietasker, pyrsistent
  Running setup.py bdist_wheel for curietasker ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-r9c8h50k/wheels/ee/b0/61/7dd6ee66fbd68d32a864bcb53b8fbead8059a59552036c0bb6
  Running setup.py bdist_wheel for pyrsistent ... done
  Stored in directory: /root/.cache/pip/wheels/1e/0e/a7/ea8661f8fe36cee188d14e7b98e57c416aa8cc72a2b2e06493
Successfully built curietasker pyrsistent
Installing collected packages: curietasker, pyrsistent
  Found existing installation: curietasker 0.6
    Uninstalling curietasker-0.6:
      Successfully uninstalled curietasker-0.6
Successfully installed curietasker-0.6 pyrsistent-0.18.1
----------------------
/usr/local/lib/python3.7/dist-packages/pyrsistent
root@875194e1cadd:/curietasker# python3 -c "import pyrsistent;print(pyrsistent)"
<module 'pyrsistent' from '/usr/local/lib/python3.7/dist-packages/pyrsistent/__init__.py'>
```

**Comment by MicroOps-cn** [comment]
> ```shell
> root@minikube:/# docker run -it --entrypoint /bin/bash curiefense/curietasker:main 
> root@875194e1cadd:/# find -name pyrsistent 2>/dev/null 
> ./usr/lib/python3.7/site-packages/pyrsistent
> root@875194e1cadd:/# python3 -c "import sys;print(sys.path)"
> ['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']
> ```
> 
> By analyzing the python environment of the image, it is found that the package cannot be found because Python is installed under `/usr/lib/python3.7/site-packages` and `/usr/lib/python3.7/site-packages` is not in `PYTHONPATH`.
> 
> Further testing：
> 
> ```shell
> root@875194e1cadd:/curietasker# rm -rf /usr/lib/python3.7/site-packages/*pyrsistent* && cd /curietasker ; pip3 install --no-cache-dir . && echo "----------------------" && find / -name  pyrsistent 2>/dev/null 
> Processing /curietasker
> Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from curietasker==0.6) (4.4.0)
> Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (5.7.1)
> Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (21.4.0)
> Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.11.3)
> Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema->curietasker==0.6)
>   Downloading https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz (100kB)
>     100% |████████████████████████████████| 102kB 767kB/s 
>   Installing build dependencies ... done
> Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.2.0)
> Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema->curietasker==0.6) (3.8.0)
> Installing collected packages: curietasker, pyrsistent
>   Found existing installation: curietasker 0.6
>     Uninstalling curietasker-0.6:
>       Successfully uninstalled curietasker-0.6
>   Running setup.py install for curietasker ... done
>   Running setup.py install for pyrsistent ... done
> Successfully installed curietasker-0.6 pyrsistent
> ----------------------
> /usr/lib/python3.7/site-packages/pyrsistent
> ```
> 
> Try to remove the option `--no-cache-dir`. It is found that the option `--no-cache-dir` is not used when executing pip. There is no problem after the installation is completed
> 
> ```
> root@875194e1cadd:/curietasker# rm -rf /usr/lib/python3.7/site-packages/*pyrsistent* && cd /curietasker ; pip3 install . && echo "----------------------" && find / -name  pyrsistent 2>/dev/null 
> Processing /curietasker
> Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from curietasker==0.6) (4.4.0)
> Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (5.7.1)
> Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.2.0)
> Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (21.4.0)
> Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema->curietasker==0.6) (4.11.3)
> Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema->curietasker==0.6)
>   Downloading https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz (100kB)
>     100% |████████████████████████████████| 102kB 369kB/s 
>   Installing build dependencies ... done
> Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema->curietasker==0.6) (3.8.0)
> Building wheels for collected packages: curietasker, pyrsistent
>   Running setup.py bdist_wheel for curietasker ... done
>   Stored in directory: /tmp/pip-ephem-wheel-cache-r9c8h50k/wheels/ee/b0/61/7dd6ee66fbd68d32a864bcb53b8fbead8059a59552036c0bb6
>   Running setup.py bdist_wheel for pyrsistent ... done
>   Stored in directory: /root/.cache/pip/wheels/1e/0e/a7/ea8661f8fe36cee188d14e7b98e57c416aa8cc72a2b2e06493
> Successfully built curietasker pyrsistent
> Installing collected packages: curietasker, pyrsistent
>   Found existing installation: curietasker 0.6
>     Uninstalling curietasker-0.6:
>       Successfully uninstalled curietasker-0.6
> Successfully installed curietasker-0.6 pyrsistent-0.18.1
> ----------------------
> /usr/local/lib/python3.7/dist-packages/pyrsistent
> root@875194e1cadd:/curietasker# python3 -c "import pyrsistent;print(pyrsistent)"
> <module 'pyrsistent' from '/usr/local/lib/python3.7/dist-packages/pyrsistent/__init__.py'>
> ```

So now there are two options:
1. Add environmental variables
For the newly packaged docker image, a new line can be added in the dockerfile:
`ENV PYTHONPATH $PYTHONPATH:/usr/lib/python3.7/site-packages/`
For the existing image, add the runtime environment variable when running
```yaml
kind: Deployment
metadata:
  name: curietasker
  namespace: curiefense
spec:
  template:
    spec:
      containers:
      - image: curiefense/curietasker:main
        env:
          name: "PYTHONPATH"
          value: "/usr/lib/python3.7/site-packages/"
        name: curietasker
```
2. remove the `--no-cache-dir` parameter. Personally, I do not recommend this scheme

**Comment by MicroOps-cn** [comment]
So now there are two options:
1. Add environmental variables
For the newly packaged docker image, a new line can be added in the dockerfile:
`ENV PYTHONPATH $PYTHONPATH:/usr/lib/python3.7/site-packages/`
For the existing image, add the runtime environment variable when running
```yaml
kind: Deployment
metadata:
  name: curietasker
  namespace: curiefense
spec:
  template:
    spec:
      containers:
      - image: curiefense/curietasker:main
        env:
          name: "PYTHONPATH"
          value: "/usr/lib/python3.7/site-packages/"
        name: curietasker
```
2. remove the `--no-cache-dir` parameter. Personally, I do not recommend this scheme
